### ISSUE TITLE
How do I install it? 

### ISSUE THREAD

**Issue by anightshade** [FrankDetzer/pwshDiskUsage#2]
$subj. Just placing it into modules directory doesn't work. Could you please include installation instructions for ppl who are new to Powershell? 
UPD: Nevermind, solved it. Didn't know that directory and module names must be identical for the system to find it.

**Comment by FrankDetzer** [comment]
Hey,

i just saw that notification. I turned off all the emails and had quite a few in my list. If theres something else i can help you with just let me know.

LG
Frankie
